---
kind: pipeline
name: znc

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    registry:
      from_secret: dockcer_registry
    repo:
      from_secret: docker_repo
    tags: latest
    username:
      from_secret: docker_username

...
