name: Build & Push to Docker Registry

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * 0'
  repository_dispatch:
    types: run-dockerpush

jobs:
  znc-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . -t ${{ secrets.DOCKER_IMAGE }}:latest

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_REGISTRY }}

      - name: Push image
        run: docker push ${{ secrets.DOCKER_IMAGE }}:latest